# Generated by Django 3.1.5 on 2021-02-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutrigardenInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('nutrigardentype', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('use', models.CharField(max_length=50)),
                ('varieties', models.CharField(max_length=50)),
                ('backyard', models.CharField(max_length=10)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('seed', models.CharField(max_length=50)),
                ('nutrigardennumber', models.IntegerField()),
                ('organic', models.IntegerField()),
                ('training', models.CharField(max_length=100)),
                ('promote', models.CharField(max_length=10)),
            ],
        ),
    ]
