# Generated by Django 3.1.5 on 2021-02-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_nutrigardeninformationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrigardeninformationmodel',
            name='afvillage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nutrigardeninformationmodel',
            name='villagename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nutrigardeninformationmodel',
            name='villagenumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
