# Generated by Django 3.1.4 on 2021-03-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20210214_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='factsheetInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('ICDSProj', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('anganwadi', models.CharField(max_length=50)),
                ('famsize', models.CharField(blank=True, max_length=50, null=True)),
                ('typeofShed', models.CharField(max_length=50)),
                ('pattern', models.CharField(max_length=50)),
                ('consumption', models.CharField(max_length=50)),
                ('typeOf', models.CharField(max_length=50)),
                ('cultTech', models.CharField(max_length=50)),
                ('seedtype', models.CharField(max_length=50)),
                ('seedSource', models.CharField(max_length=50)),
                ('seedbnkloc', models.CharField(blank=True, max_length=50, null=True)),
                ('fertType', models.CharField(max_length=50)),
                ('fertSour', models.CharField(max_length=50)),
                ('vermigrade', models.CharField(max_length=50)),
                ('pest', models.CharField(max_length=50)),
                ('fence', models.CharField(max_length=50)),
                ('irrig', models.CharField(max_length=50)),
                ('water', models.CharField(max_length=50)),
                ('resrcLvrgd', models.CharField(max_length=50)),
                ('govt', models.CharField(blank=True, max_length=50, null=True)),
                ('prov', models.CharField(max_length=50)),
                ('provPlace', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
