# Generated by Django 3.1.6 on 2021-03-16 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0005_factsheetinformationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='consumption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='cultTech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='fence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='fertSour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='fertType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='irrig',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='pattern',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='pest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='prov',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='resrcLvrgd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='seedSource',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='seedtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='typeOf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='typeofShed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='vermigrade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factsheetinformationmodel',
            name='water',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
