# Generated by Django 3.1.4 on 2021-03-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20210316_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='ICDSProj',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='anganwadi',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='cultTech',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='famsize',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='fence',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='fertSour',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='fertType',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='govt',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='irrig',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='pest',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='prov',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='provPlace',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='resrcLvrgd',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='seedSource',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='seedbnkloc',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='seedtype',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='typeOf',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='typeofShed',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='vermigrade',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='village',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='water',
        ),
    ]
