# Generated by Django 3.1.4 on 2021-03-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20210317_0336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factsheetinformationmodel',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='factsheetinformationmodel',
            old_name='state',
            new_name='State',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='Famsize',
            field=models.CharField(blank=True, choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('more than 6', 'More than 6')], max_length=25),
        ),
    ]
