# Generated by Django 3.1.4 on 2021-03-18 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0008_auto_20210317_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='Famsize',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='State',
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='ICDSProj',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='anganwadi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='consump',
            field=models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Only self-consumption (includes sharing with neighbors)', 'Only self-consumption (includes sharing with neighbors)'), ('Selling surplus', 'Selling surplus'), ('Selling surplus with value addition', 'Selling surplus with value addition')], default='Choose Your Option', max_length=100),
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='famsize',
            field=models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('more than 6', 'More than 6')], default='Choose Your Option', max_length=100),
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='patt',
            field=models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Circular', 'Circular'), ('Rectangle/Square', 'Rectangle/Square'), ('Other Pattern', 'Other Pattern')], default='Choose Your Option', max_length=100),
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='typeOf',
            field=models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Fruits/ seeds/ vegetables', 'Fruits/ seeds/ vegetables'), ('Vegetarian + Poultry', 'Vegetarian + Poultry'), ('Vegetarian + Poultry + Others', 'Vegetarian + Poultry + Others')], default='Choose Your Option', max_length=100),
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='typeofShed',
            field=models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Open Field', 'Open Field'), ('Poly House', 'Poly House'), ('Shed net', 'Shed net')], default='Choose Your Option', max_length=100),
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factsheetinformationmodel',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
