# Generated by Django 3.1.4 on 2021-03-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20210318_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='factsheetDynamicIndicatorsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultTech', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Raised bed', 'Raised bed'), ('Circular bed', 'Circular bed'), ('Container cultivation', 'Container cultivation'), ('Vertical gardening', 'Vertical gardening'), ('Other', 'Other')], default='Choose Your Option', max_length=100, null=True)),
                ('seedtype', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Indegenious', 'Indegenious'), ('Hybrid', 'Hybrid')], default='Choose Your Option', max_length=100, null=True)),
                ('seedSource', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Market', 'Market'), ('Household', 'Household'), ('Seed Bank', 'Seed Bank'), ('Government Department (Horticulture, KVK etc.)', 'Government Department (Horticulture, KVK etc.)'), ('NGOs/ CSOs', 'NGOs/ CSOs'), ('Others', 'Others')], default='Choose Your Option', max_length=100, null=True)),
                ('seedbnkloc', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Village', 'Village'), ('Panchayat', 'Panchayat'), ('Block', 'Block'), ('Others', 'Others')], default='Choose Your Option', max_length=100, null=True)),
                ('fertType', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Chemical', 'Chemical'), ('Organic manure', 'Organic manure'), ('Natural', 'Natural')], default='Choose Your Option', max_length=100, null=True)),
                ('fertSour', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Household vermicompost', 'Household vermicompost'), ('Market', 'Market'), ('Livestock', 'Livestock'), ('Government', 'Government')], default='Choose Your Option', max_length=100, null=True)),
                ('vermigrade', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Agnihotra', 'Agnihotra'), ('Jeevamurat', 'Jeevamurat'), ('Steramil', 'Steramil'), ('Neem', 'Neem'), ('Humic', 'Humic'), ('Others', 'Others')], default='Choose Your Option', max_length=100, null=True)),
                ('pest', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Healthy seedling production', 'Healthy seedling production'), ('Infected shoot clipping', 'Infected shoot clipping'), ('Pheromone trap', 'Pheromone trap'), ('Minimal use of pesticides', 'Minimal use of pesticides'), ('Others', 'Others')], default='Choose Your Option', max_length=100, null=True)),
                ('fence', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Natural (mud, bamboo, trees, shrubs, tree leaves etc.)', 'Natural (mud, bamboo, trees, shrubs, tree leaves etc.)'), ('Metal/ wire Fencing', 'Metal/ wire Fencing'), ('Cement/ brick wall', 'Cement/ brick wall'), ('Any cloth type material/ tarpaulin', 'Any cloth type material/ tarpaulin'), ('Others', 'Others')], default='Choose Your Option', max_length=100, null=True)),
                ('irrig', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Drip', 'Drip'), ('Flood', 'Flood'), ('Watering by pot', 'Watering by pot'), ('Rain-fed', 'Rain-fed'), ('Others', 'Others')], default='Choose Your Option', max_length=100, null=True)),
                ('water', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Pond', 'Pond'), ('River', 'River'), ('Tube Well', 'Tube well'), ('Well', 'well'), ('Rain', 'Rain'), ('Lake', 'Lake'), ('Pipe water', 'Pipe water'), ('Others', 'Others')], default='Choose Your Option', max_length=100, null=True)),
                ('resrcLvrgd', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Self', 'Self'), ('Government Scheme', 'Government Scheme'), ('NGOs/ CSOs', 'NGOs/ CSOs'), ('Others', 'Others')], default='Choose Your Option', max_length=100, null=True)),
                ('govt', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('MGNREGA', 'MGNREGA'), ('ICDS', 'ICDS'), ('Education', 'Education'), ('Agriculture', 'Agriculture'), ('Panchayat', 'Panchayat'), ('Others', 'Others')], default='Choose Your Option', max_length=100, null=True)),
                ('prov', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('yes', 'Yes'), ('no', 'No')], default='Choose Your Option', max_length=100, null=True)),
                ('provPlace', models.CharField(blank=True, choices=[('', 'Choose Your Option'), ('Cold storage', 'Cold storage'), ('Open storage', 'Open storage'), ('Others', 'Others')], default='Choose Your Option', max_length=100, null=True)),
            ],
        ),
    ]
