# Generated by Django 3.1.5 on 2021-03-18 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0010_factsheetdynamicindicatorsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='factsheetdynamicindicatorsmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='financialExpensesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soilPrep', models.CharField(blank=True, max_length=100, null=True)),
                ('fertilizers', models.CharField(blank=True, max_length=100, null=True)),
                ('seeds', models.CharField(blank=True, max_length=100, null=True)),
                ('cultTools', models.CharField(blank=True, max_length=100, null=True)),
                ('fence', models.CharField(blank=True, max_length=100, null=True)),
                ('transportation', models.CharField(blank=True, max_length=100, null=True)),
                ('labor', models.CharField(blank=True, max_length=100, null=True)),
                ('irrigation', models.CharField(blank=True, max_length=100, null=True)),
                ('miscellaneous', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
