# Generated by Django 3.1.4 on 2021-03-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20210318_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialexpensesmodel',
            name='cultToolsDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialexpensesmodel',
            name='fenceDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialexpensesmodel',
            name='fertilizersDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialexpensesmodel',
            name='irrigationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialexpensesmodel',
            name='laborDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialexpensesmodel',
            name='miscellaneousDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialexpensesmodel',
            name='seedsDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialexpensesmodel',
            name='soilPrepDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialexpensesmodel',
            name='transportaionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='cultTools',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='fence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='fertilizers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='irrigation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='labor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='miscellaneous',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='seeds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='soilPrep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='transportation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
