# Generated by Django 3.1.4 on 2021-03-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20210319_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='soilPrep',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
