# Generated by Django 3.1.4 on 2021-03-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20210319_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='cultToolsDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='fenceDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='fertilizersDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='irrigationDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='laborDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='miscellaneousDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='seedsDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='soilPrepDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='transportaionDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
