# Generated by Django 3.1.4 on 2021-03-19 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0014_auto_20210319_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factsheetdynamicindicatorsmodel',
            name='prov',
            field=models.CharField(blank=True, choices=[('', 'yes/no'), ('yes', 'Yes'), ('no', 'No')], default='Choose Your Option', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='cultToolsDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='fenceDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='fertilizersDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='irrigationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='laborDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='miscellaneousDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='seedsDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='soilPrepDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialexpensesmodel',
            name='transportaionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='outputIndicatorsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantType', models.CharField(blank=True, max_length=100, null=True)),
                ('sowingDate', models.DateField(blank=True, null=True)),
                ('harvestDate', models.DateField(blank=True, null=True)),
                ('seedQuantity', models.IntegerField(blank=True, null=True)),
                ('harvestQuant', models.IntegerField(blank=True, null=True)),
                ('lostQuant', models.CharField(blank=True, choices=[('', 'yes/no'), ('yes', 'Yes'), ('no', 'No')], max_length=100, null=True)),
                ('income', models.CharField(blank=True, max_length=100, null=True)),
                ('whereSold', models.CharField(blank=True, choices=[('', 'Select'), ('Middleman', 'Middleman'), ('Institution', 'Institution'), ('direct', 'Direct'), ('CSOs', 'CSOs')], max_length=100, null=True)),
                ('finishingMonth', models.CharField(blank=True, choices=[('', 'Select'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=100, null=True)),
                ('soldQuant', models.IntegerField(blank=True, null=True)),
                ('consumedQuant', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
