# Generated by Django 3.1.4 on 2021-05-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_auto_20210321_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factsheetinformationmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='financialexpensesmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nutrigardeninformationmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='outputindicatorsmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='afifpartner',
        ),
        migrations.DeleteModel(
            name='factsheetDynamicIndicatorsModel',
        ),
        migrations.DeleteModel(
            name='factsheetInformationModel',
        ),
        migrations.DeleteModel(
            name='financialExpensesModel',
        ),
        migrations.DeleteModel(
            name='NutrigardenInformationModel',
        ),
        migrations.DeleteModel(
            name='outputIndicatorsModel',
        ),
    ]
