# Generated by Django 3.1.4 on 2021-05-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_auto_20210522_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinformationmodel',
            name='user',
        ),
    ]
