# Generated by Django 3.1.4 on 2021-06-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadpicturemodel',
            name='picture',
            field=models.ImageField(blank=True, default='PoshanVatikaPics/noImage.jpg', null=True, upload_to='PoshanVatikaPics/'),
        ),
        migrations.AlterField(
            model_name='uploadwellpicturemodel',
            name='picture',
            field=models.ImageField(blank=True, default='WellPics/noImage.jpg', null=True, upload_to='WellPics/'),
        ),
    ]
