# Generated by Django 3.1.4 on 2021-05-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210505_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadpicturemodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploadPics/'),
        ),
        migrations.AlterField(
            model_name='uploadwellpicturemodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploadPics/'),
        ),
    ]
