# Generated by Django 3.1.5 on 2021-02-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210214_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='uploadPics/')),
                ('area', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
    ]
