# Generated by Django 3.1.4 on 2021-05-06 08:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20210506_0746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WellPictureLocation',
            new_name='WellPictureLocationModel',
        ),
    ]
