# Generated by Django 3.1.4 on 2021-05-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210506_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturelocation',
            name='picture_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wellpicturelocationmodel',
            name='picture_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
