# Generated by Django 3.1.4 on 2021-05-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210506_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturelocation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wellpicturelocationmodel',
            name='user',
        ),
    ]
