# Generated by Django 3.1.4 on 2021-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210506_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturelocation',
            name='picture_name',
            field=models.FileField(blank=True, max_length=30, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wellpicturelocationmodel',
            name='picture_name',
            field=models.FileField(blank=True, max_length=30, null=True, upload_to=''),
        ),
    ]
